### ISSUE TITLE
h_len is zero

### ISSUE THREAD

**Issue by lamhk** [kkuette/TradzQAI#1]
Hi kkuette,

I tried to the run the "-m eval" and get the following warning.  Will this affect the result?  Thanks.
========
  File "...TradzQAI-master/core/environnement/base/base_env.py", line 373, in eval_processing
    avg_profit /= h_len
ZeroDivisionError: division by zero
========

**Comment by kkuette** [comment]
Hi lamhk,

This problem append because you didnt finished at least one eval episode.
I've already fixed it.
