### ISSUE TITLE
how to perform test using the trained model

### ISSUE THREAD

**Issue by lamhk** [kkuette/TradzQAI#2]
Hi kkuette,

After the training, how can I test a new datasets using the trained model?  Thanks.

Regards,
lamhk

**Comment by kkuette** [comment]
When you train a model, a ```save/``` directory is created.
The config, the logs and the model are saved in the ```model name```  (like ```DQN```) directory in ```save/```.
the path should be ```./save/model_name_id```.
if you use the same settings as the settings of one of the model in the save directory it will automatically use the saved model.
In the default config directory (```./config/```), in the file ```environnement.json```, you can change the line ```"data_directory": "data/"``` by ```"data_directory":"mydirectory"```.
It take all files in all directory within the provided directory.
Filepath used for training and eval are saved in ```<mode>_data_datetime.txt``` in your save directory.
Once you change the ```data_directory``` path you can launch the eval by using ```py run.py -m eval```.

**Comment by lamhk** [comment]
Hi kuette,

when I use "-g on" to perform training, I have the following error "Traceback (most recent call last):
  File "/home/lamhk/TradzQAI-master/GUI/main_window.py", line 170, in lock_error
    self.Build_Primary_Window()
  File "/home/lamhk/TradzQAI-master/GUI/main_window.py", line 590, in Build_Primary_Window
    self.overview = OverviewWindow(self.main_tab, self.env)
  File "/home/lamhk/TradzQAI-master/GUI/overview_window.py", line 26, in __init__
    GB.addWidget(self.Agent_Inventory_Init(env), 0, 2, 2, 1)
  File "/home/lamhk/TradzQAI-master/GUI/overview_window.py", line 75, in Agent_Inventory_Init
    GBox.setFixedSize(h,w)
UnboundLocalError: local variable 'w' referenced before assignment
".

Thanks.

**Comment by kkuette** [comment]
It should be good right now, but keep in mind that the gui is kind of old, it slow down the whole process du to it's recurrent update.
I will update it when i'll finish the cbpro API integration.

**Comment by lamhk** [comment]
Hi kkuette, thanks for your quick response. I tried to perform the training by using the default command line or add -m train.  But the result always shows "0it [00:00, ?it/s]" in a single line.  Anything wrong with my setting as I can see data DAX30... in the data directory and the configuration file also shows "data/" as the data_directoty.  Thanks.

Regards,
lamhk

**Comment by kkuette** [comment]
Now you have to pull from your git directory.
And the worker is a thread that loop all datasets, episodes, steps, located in ```TradzQAI/core/worker/```.
