### ISSUE TITLE
Using other exchanges

### ISSUE THREAD

**Issue by AlconDivino** [kkuette/TradzQAI#22]
Is it possible to change the exchanges for the life exchanges? 
Where to start? 
If you give me a starting point i could try and do it myself and make a pull request afterwards

**Comment by kkuette** [comment]
Hi,
you can do a wrapper for any exchange you want based on [this wrapper](https://github.com/kkuette/TradzQAI/blob/master/TradzQAI/API/cbpro/cbpro_wrapper.py).

Check the [API](https://github.com/kkuette/TradzQAI/tree/master/TradzQAI/API) for more details.

Sorry for the lack of documentation :/
