### ISSUE TITLE
How to specify which trained model to be used for "eval"

### ISSUE THREAD

**Issue by lamhk** [kkuette/TradzQAI#5]
Hi, I trained one model using 1 episode (PPO_0 and 1) and another one with 100 episodes (PPO_2).  However, when I tried to perform the -m eval, i got the same result.  I believe it used the same model even I have a trained model with 100 episodes.  Please advise how i could specify which PPO_# to be used for eval?  Thx.

**Comment by kkuette** [comment]
You just need to set the same settings in ```TradzQAI/config/``` and ```TradzQAI/save/PPO_#/config/```.
Each time you start ```TradzQAI```, it check if the current settings already exists in ```save/``` directory, if not it create a new directory, else it take the first directory with the same settings it encounter.
